### ISSUE TITLE
help on run trailling stop 

### ISSUE THREAD

**Issue by 9121511** [jsappme/node-binance-trader#13]
(node:22014) UnhandledPromiseRejectionWarning: FetchError: request to https://api.binance.com/api/v3/order?symbol=BNBETH&orderId=33545358&timestamp=1531445349308&signature=295756b3ebc8a9f053d6f5eb7779c9c76315cedcae8996783daa76a964d1f1c8 failed, reason: getaddrinfo ENOTFOUND api.binance.com api.binance.com:443
    at ClientRequest.<anonymous> (/home/user/Desktop/cd/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:22014) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22014) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jsappme** [comment]
it seems your internet connection might not be stable enough. This issue is not related to the bot itself.
