### ISSUE TITLE
Issues with `talib`

### ISSUE THREAD

**Issue by aolin480** [jsappme/node-binance-trader#35]
Is talib (https://www.npmjs.com/package/talib) a requirement for this app to work? I tried running `npm run bt`, but it said it couldn't find `talib`, but when I `npm install talib --save-dev`, `talib` errors out on the install. I am running node@8 too. Not sure if that has any issues, but. The other node commands worked, except for `npm run trader`, I get output, but on each call, I am getting an undefined string. Here's an example output of that

```
=> BUY SIGNAL EOSBTC undefined
(node:26329) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'padStart' of undefined
    at Socket.socket.on (/Volumes/localdev/crypto/node-binance-trader/trader.js:46:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:26329) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
```

### Here's the error when doing `npm install talib --save-dev`
```
../src/talib.cpp:1086:1: error: C++ requires a type specifier for all declarations
NODE_MODULE_INIT(/* exports, module, context */) {
^
../src/talib.cpp:1087:10: error: use of undeclared identifier 'exports'
    Init(exports, context);
         ^
../src/talib.cpp:1087:19: error: use of undeclared identifier 'context'
    Init(exports, context);
                  ^
3 warnings and 3 errors generated.
make: *** [Release/obj.target/talib/src/talib.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node@8/8.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/Cellar/node@8/8.16.0/bin/node" "/usr/local/Cellar/node@8/8.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /Users/xxx/temp/node_modules/talib
gyp ERR! node -v v8.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/Users/xxx/temp/package.json'
npm WARN temp No description
npm WARN temp No repository field.
npm WARN temp No README data
npm WARN temp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! talib@1.1.2 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the talib@1.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2019-06-16T17_40_02_133Z-debug.log
Execution time: 0h:00m:24s sec
```

**Comment by aolin480** [comment]
Ah, it looks like it is a node version issue. I was able to install this package on node v12
