### ISSUE TITLE
Can't connect to NBT anymore: "Crypto Operation Failed"

### ISSUE THREAD

**Issue by JoeSchr** [jsappme/node-binance-trader#62]
Hi there, since a few day, I can't connect the trader to NBT anymore.

I added a `socket.on('connect_error', (e) => ....` hook to see what's going on.
this is the error i got back:

```JS
NBT auto trader running.
Connection error Error: xhr poll error
    at XHR.Transport.onError (/home/joe/projects/trader/node-binance-trader/node_modules/engine.io-client/lib/transport.js:68:13)
    at Request.<anonymous> (/home/joe/projects/trader/node-binance-trader/node_modules/engine.io-client/lib/transports/polling-xhr.js:132:10)
    at Request.Emitter.emit (/home/joe/projects/trader/node-binance-trader/node_modules/component-emitter/index.js:145:20)
    at Request.onError (/home/joe/projects/trader/node-binance-trader/node_modules/engine.io-client/lib/transports/polling-xhr.js:314:8)
    at Timeout._onTimeout (/home/joe/projects/trader/node-binance-trader/node_modules/engine.io-client/lib/transports/polling-xhr.js:274:12)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  type: 'TransportError',
  description: Error: Unable to load PFX certificate
      at Object.createSecureContext (node:_tls_common:334:17)
      at Object.connect (node:_tls_wrap:1602:48)
      at Agent.createConnection (node:https:137:22)
      at Agent.createSocket (node:_http_agent:334:26)
      at Agent.addRequest (node:_http_agent:285:10)
      at new ClientRequest (node:_http_client:322:16)
      at Object.request (node:https:333:10)
      at Object.<anonymous> (/home/joe/projects/trader/node-binance-trader/node_modules/agent-base/patch-core.js:25:22)
      at /home/joe/projects/trader/node-binance-trader/node_modules/socks-proxy-agent/node_modules/agent-base/patch-core.js:23:20
      at XMLHttpRequest.send (/home/joe/projects/trader/node-binance-trader/node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js:495:17) {
    code: 'ERR_CRYPTO_OPERATION_FAILED'
  }
}
```

**Comment by JoeSchr** [comment]
Maybe the ssl cert elapsed or something?

**Comment by dargmuesli** [comment]
I can connect on my Arch Linux, but not on my Debian buster 🤔

**Comment by dargmuesli** [comment]
Which Node / npm version are you using and what's your OS?

**Comment by dargmuesli** [comment]
This problem occurred to me when using Node 15. I'm now using Node 14 and the issue no longer persists.

Btw, I'm using Docker.

**Comment by JoeSchr** [comment]
Thanks, I also figured while working on your other request, that it works on my other machine. Both are arch though and I thought running with Node 14. Have to double check

**Comment by JoeSchr** [comment]
>  I'm now using Node 14 and the issue no longer persists.

Yes, that did it!
