### ISSUE TITLE
Error: ETIMEDOUT request

### ISSUE THREAD

**Issue by ghostnetrn** [jsappme/node-binance-trader#63]
Error: ETIMEDOUT
    at Timeout.<anonymous> (/root/node-binance/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ETIMEDOUT',
  connect: true
}
(node:88756) UnhandledPromiseRejectionWarning: Error: ETIMEDOUT
    at Timeout.<anonymous> (/root/node-binance/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:88756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:88756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ghostnetrn** [comment]
The machine was not pinging the api.binance.com server. I released it on the firewall.
