### ISSUE TITLE
Error running npm install

### ISSUE THREAD

**Issue by ronnyandre** [jsappme/node-binance-trader#68]
```
$ npm i --unsafe-perm 
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> tulind@0.8.18 install /Users/myself/Documents/node-binance-trader/node_modules/tulind
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.18/Release/tulind-v0.8.18-node-v83-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for tulind@0.8.18 and node@14.8.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node/14.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/myself/Documents/node-binance-trader/node_modules/tulind/lib/binding/Release/node-v83-darwin-x64/tulind.node" "--module_name=tulind" "--module_path=/Users/myself/Documents/node-binance-trader/node_modules/tulind/lib/binding/Release/node-v83-darwin-x64" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /Users/myself/Documents/node-binance-trader/node_modules/tulind
gyp ERR! node -v v14.8.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/14.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/myself/Documents/node-binance-trader/node_modules/tulind/lib/binding/Release/node-v83-darwin-x64/tulind.node --module_name=tulind --module_path=/Users/myself/Documents/node-binance-trader/node_modules/tulind/lib/binding/Release/node-v83-darwin-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/myself/Documents/node-binance-trader/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Darwin 19.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/14.8.0/bin/node" "/Users/myself/Documents/node-binance-trader/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/myself/Documents/node-binance-trader/node_modules/tulind
node-pre-gyp ERR! node -v v14.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/14.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/myself/Documents/node-binance-trader/node_modules/tulind/lib/binding/Release/node-v83-darwin-x64/tulind.node --module_name=tulind --module_path=/Users/myself/Documents/node-binance-trader/node_modules/tulind/lib/binding/Release/node-v83-darwin-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN node-binance-trader@0.2.4 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tulind@0.8.18 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tulind@0.8.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myself/.npm/_logs/2021-02-18T10_27_15_866Z-debug.log
```

**Comment by ronnyandre** [comment]
Running in Heroku solves everything

**Comment by timotheeguerinrb** [comment]
I had the same problem, solved by doing this : 

`sudo yum groupinstall "Development Tools"
`npm install tulind
